# -*- coding: utf-8 -*-
"""HW10_Exercise1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NIQsx6CV4wHmAFjhLXV06ho8AYT_d3Fv
"""

#Exercise 1:
from tensorflow.keras.datasets import mnist
import cv2
from google.colab.patches import cv2_imshow
import numpy as np
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, Dense, Flatten, MaxPool2D

(X_train, y_train), (X_test, y_test) = mnist.load_data()
X_train = X_train.reshape(60000, 28, 28, 1)
X_test = X_test.reshape(10000, 28, 28, 1)
X_train = X_train.astype("float32") / 255
X_test = X_test.astype("float32") / 255

print(y_train)
print(y_train.shape)
print(y_train[0])
y_train = to_categorical(y_train)
print(f'categorical data:\n{y_train}')
print(y_train.shape)
print(y_train[0])

cnn = Sequential()

cnn.add(Conv2D(filters=64, kernel_size=(3, 3), activation="relu", input_shape=(28, 28, 1)))
cnn.add(MaxPool2D(pool_size=(2, 2)))
cnn.add(Conv2D(filters=128, kernel_size=(3, 3), activation="relu"))
cnn.add(MaxPool2D(pool_size=(2, 2)))
cnn.add(Conv2D(filters=256, kernel_size=(3, 3), activation="relu", padding = 'same'))
cnn.add(MaxPool2D(pool_size=(2, 2)))
cnn.add(Conv2D(filters=512, kernel_size=(3, 3), activation="relu", padding = 'same'))
cnn.add(MaxPool2D(pool_size=(2, 2)))
cnn.add(Flatten())
cnn.add(Dense(units=128, activation="relu"))
cnn.add(Dense(units=10, activation="softmax"))

cnn.summary()

cnn.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["accuracy"])

cnn.fit(X_train, y_train, epochs=5, batch_size=64, validation_split=0.1)

# Evaluate accuracy on test dataset...
# Convert y_test to one-hot encoded format
print(f'y_test shape (before one-hot encoding): {y_test.shape}')
y_test = to_categorical(y_test) # convert to one-hot encoded labels (shape (None, 10)
print(f'y_test shape (after one-hot encoding): {y_test.shape}')

# ...Evaluate accuracy on test dataset
test_loss, test_accuracy = cnn.evaluate(X_test, y_test)
print(f"Test accuracy: {test_accuracy:.4f}, Test loss: {test_loss:.4f}")

# After defining the model (cnn), print weights for Conv2D layers
for i, layer in enumerate(cnn.layers):
    if isinstance(layer, Conv2D): # Check if the layer is Conv2D
        weights, biases = layer.get_weights()
        print(f"Conv2D Layer {i} Weights (Filters):")
        print(weights.shape) # Shape of the weight tensor
        print(weights)
        print(f"Conv2D Layer {i} Biases:")
        print(biases.shape)
        print(biases)

def myPredict(image):
    image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    image = cv2.resize(image, (28, 28))
    image = image.reshape((1, 28, 28, 1))
    # MNIST images have dark background and light foreground,
    # we need to correct our images to match that
    image = cv2.bitwise_not(image)
    prediction = cnn.predict(image)[0]
    return np.argmax(prediction)

#5
image = cv2.imread('five.jpg')
cv2_imshow(image)
print(f'The prediction is: {myPredict(image)}')

#3
image = cv2.imread('three.png')
cv2_imshow(image)
print(f'The prediction is: {myPredict(image)}')

#2
image = cv2.imread('two.png')
cv2_imshow(image)
print(f'The prediction is: {myPredict(image)}')